builds:
- main: ./cmd/reloader
  binary: reloader
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - ppc64le
  ldflags:
  - -s -w
  - -X github.com/stakater/Reloader/internal/pkg/metadata.Version={{.Version}}
  - -X github.com/stakater/Reloader/internal/pkg/metadata.Commit={{.Commit}}
  - -X github.com/stakater/Reloader/internal/pkg/metadata.BuildDate={{.Date}}
archives:
- name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
changelog:
  # It will be generated manually as part of making a new GitHub release
  disable: true
env_files:
  github_token: /home/jenkins/.apitoken/hub
