name: Push Documentation Changes

on:
  push:
    branches:
      - master
    paths:
      - '.markdownlint.yaml'
      - '.vale.ini'
      - 'Dockerfile-docs'
      - 'docs-nginx.conf'
      - 'docs/**'
      - 'README.md'
      - 'theme_common'
      - 'theme_override'

jobs:
  push:
    uses: stakater/.github/.github/workflows/push_container.yaml@v0.0.82
    with:
      DOCKER_FILE_PATH: Dockerfile-docs
      RELEASE_BRANCH: master
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater/docs
      CONTAINER_REGISTRY_USERNAME: stakater-user
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
